# File .github/workflows/ci.yml

name: Upload OpenAPI spec to Stainless and Bump.sh

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update-docs:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push spec file to Stainless
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          project_name: lobehub-sit
          # Note: this should be the path to your specification file
          input_path: './openapi.yml'
          # Note: this file will be your spec extended with code samples
          output_path: './openapi-with-code-samples.json'

      - name: Deploy API docs to Bump.sh
        uses: bump-sh/github-action@v1
        with:
          doc: 81f3b835-4b61-4d99-848c-3b2e8b7a4350
          token: ${{secrets.BUMP_TOKEN}}
          # Note: be sure this is pointing to the extended spec file
          file: './openapi-with-code-samples.json'

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff with Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: 81f3b835-4b61-4d99-848c-3b2e8b7a4350
          token: ${{secrets.BUMP_TOKEN}}
          # Note: this should be the path to your specification file
          file: './openapi.yml'
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
